### 컬럼 삭제

In [1]:
import pandas as pd

dataframe = pd.DataFrame(data={
    "eno": [1, 2, 3, 4, 5],
    "name": ["춘봄이", "하여름", "추가을", "동겨울", "춘순이"],
    "dept": ["개발팀", "분석팀", "홍보팀", "인사팀", "설계팀"],
    "date": [
        pd.to_datetime("2015-09-22"),
        pd.to_datetime("2016-09-22"),
        pd.to_datetime("2017-09-22"),
        pd.to_datetime("2018-09-22"),
        pd.to_datetime("2019-09-22")
    ],
    "salary": [8000, 7500, 7300, 7200, 7700]
})

dataframe

   eno name dept       date  salary
0    1  춘봄이  개발팀 2015-09-22    8000
1    2  하여름  분석팀 2016-09-22    7500
2    3  추가을  홍보팀 2017-09-22    7300
3    4  동겨울  인사팀 2018-09-22    7200
4    5  춘순이  설계팀 2019-09-22    7700

In [2]:
dataframe.drop(
    columns=["date", "salary"], 
    inplace=True
)

dataframe

   eno name dept
0    1  춘봄이  개발팀
1    2  하여름  분석팀
2    3  추가을  홍보팀
3    4  동겨울  인사팀
4    5  춘순이  설계팀